version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

# version: '3.5'

# services:
#   postgres:
#     container_name: postgres_container
#     image: postgres
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       PGDATA: /data/postgres
#     volumes:
#        - postgres:/data/postgres
#     ports:
#       - "5432:5432"
#     networks:
#       - postgres
#     restart: unless-stopped
  
#   pgadmin:
#     container_name: pgadmin_container
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: masbahuddin65@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: password
#       PGADMIN_CONFIG_SERVER_MODE: 'False'
#     volumes:
#        - pgadmin:/var/lib/pgadmin

#     ports:
#       - "5050:80"
#     networks:
#       - postgres
#     restart: unless-stopped

# networks:
#   postgres:
#     driver: bridge

# volumes:
#     postgres:
#     pgadmin: